RoR Blog Web App: Milestone-2 Processing dta
Profsain/ror-blog-app pull request #2
Opened 2022-09-23 20:45 UTC by Profsain

### I completed this part of the project by fulfilling the requirement below:

2022-09-23 21:16 UTC, Mihndim2020 requested changes
### Hi @Profsain, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Clean/Organized code
:heavy_check_mark: Descriptive Readme file

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)

# Status: Requires Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 21:16 UTC, Mihndim2020 commented on app/models/author.rb
> +end
- [ ] As it is a requirement for this project, please ensure associations between models are set up correctly according to the given [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png). Kindly create an association between user, posts, comments and likes. Something like so: 
```ruby
has_many :posts, foreign_key: 'author_id'
has_many :comments, foreign_key: 'author_id'
has_many :likes, foreign_key: 'author_id'
```

- [ ] According to the project requirements, User model should have a  method that returns 3 most recent posts. Please kindly implement that. Something like so: 

```ruby
def recent_post
  posts.order('created_at Desc').limit(3)
end
```

2022-09-23 21:16 UTC, Mihndim2020 commented on app/models/post.rb
> +  belongs_to :author
- [ ] As it is a requirement for this project, please ensure associations between models are set up correctly according to the given [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png). Kindly create an association between posts, user, comments and likes. Something like so: 
```ruby
belongs_to :author, class_name: 'User'
has_many :comments
has_many :likes
```

- [ ] According to the project requirements, the Post model should have a method that updates the posts counter for a user. Something like so: 
```ruby
def update_post_counter
  author.increment!(:posts_counter)
end
```
Please kindly fix that.

- [ ] According to the project requirements, the Post model should have a method that returns the 5 most recent comments for a given post. Something like so: 
```ruby
def recent_comments
  comments.order('created_at Desc').limit(5)
end
```

Please kindly fix that.

2022-09-23 21:16 UTC, Mihndim2020 commented on app/models/comment.rb
>    belongs_to :post
- [ ]  As it is a requirement for this project, the Comment model should have a method that updates the comments counter for a post.  Something like so: 
 ```ruby
def update_comments_counter
  post.increment!(:comments_counter)
end
```
Please kindly fix that.

2022-09-23 21:16 UTC, Mihndim2020 commented on app/models/like.rb
>    belongs_to :post
- [ ]  As it is a requirement for this project, the Like model should have a method that updates the likes counter for a post.  Something like so: 
 ```ruby
def update_likes_counter
  post.increment!(:likes_counter)
end
```
Please kindly fix that.

2022-09-23 21:22 UTC, Profsain commented on app/models/author.rb
> +end
Thank you for your feedback.
I will implement the changes required.

2022-09-23 22:09 UTC, tufoinnkuo10 requested changes
Hi @Profsain 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated


Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-09-23 22:09 UTC, tufoinnkuo10 commented on app/models/comment.rb
> +  belongs_to :author
- [ ] please like the previous reviewer noted, the Comment model should have a method that updates the comments counter for a post. Something like so:
```
def update_comments_counter
 post.increment!(:comments_counter)
end
```

2022-09-23 22:09 UTC, tufoinnkuo10 commented on app/models/post.rb
> +  belongs_to :author, class_name: 'Author'
- [ ] pleasr like the previous reviewer noted,the Post model should have a method that updates the posts counter for a user. Something like so:
```
def update_post_counter
  author.increment!(:posts_counter)
end
```

2022-09-24 06:20 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 11:47 UTC, merged